### ISSUE TITLE
SB_Аuth

### ISSUE THREAD

**Issue by inkognito07** [CrazyHackGUT/SB_Material_Design#11]
Добрый день , хотелось бы что бы Вы вмонтировали в свой плагин - плагин Sb_Auth. Суть плагина в том что бы администратор не смог зайти на сервер пока не введет пароль от своей админки. Так как я являюсь обладателем сервера v34 , то эта функция крайне необходима, потому что часто взламывают STEAM_ID администратора и играют на этом стиме с читами.
Сейчас в вашем плагине это работает не совсем так. На вашем плагине принцип таков: админка не будет работать пока не ввести пароль от нее, НО при этом можно спокойно играть на сервере не вводя пароль нее.

**Comment by Meowmurmur** [comment]
Так было во всех версиях СБ. Юзай http://hlmod.ru/threads/steamid-protect-with-sql.11177/

**Comment by inkognito07** [comment]
Есть по проще, пол часа искал и вот нашел плагин, и для обладателей серверов v34 это не заменимая вещь.

[Sb_Auth.zip](https://github.com/CrazyHackGUT/SB_Material_Design/files/569802/Sb_Auth.zip)

**Comment by CrazyHackGUT** [comment]
Рассмотрю ваше предложение, как только буду дома. Это примерно через четыре-пять часов :)

**Comment by CrazyHackGUT** [comment]
Сделаем отдельным плагином. Пароль будет браться из админки СБ, из раздела "Серверный пароль". Вы, должно быть, видели его ранее?)

**Comment by inkognito07** [comment]
Видел. Как я понял вы его модернизируете , теперь плагин будет проверять на наличие пароля от админки , и в зависимости от этого плагин будет пускать или же не пускать админа на сервер ? И если это так то это круто, хотя я всегда ставлю пароль на админку , ведь в34 же =))

**Comment by inkognito07** [comment]
И он вроде из-за этого Сб выдает ошибки. 

`L 11/05/2016 - 11:51:10: [SM] Displaying call stack trace for plugin "sb_auth.smx":
L 11/05/2016 - 11:51:10: [SM]   [0]  Line 44, C:\Users\\Desktop\  \scripting\sb_auth.sp::OnClientAuthorized()
L 11/05/2016 - 11:51:10: [SM] Native "SQL_TQuery" reported: Invalid database Handle 0 (error: 4)`

**Comment by CrazyHackGUT** [comment]
Да, модернизируем. Вернее, вообще с нуля сейчас переписываем :)

**Comment by inkognito07** [comment]
И еще , сейчас обратился в ТП майарены , с проблемой:иногда  Крашится/Зависает сервер при смене карты , они мне сказали что бы я отключил sourcebans и проверил.  И кстати да, этого у меня не было пока я не установил sourcebans. Но я все же проверю с выключенным сб.
