### ISSUE TITLE
 Ошибка системы  [256] Smarty error: [in page_bans.tpl line 556]

### ISSUE THREAD

**Issue by RED4911** [CrazyHackGUT/SB_Material_Design#14]
[256] Smarty error: [in page_bans.tpl line 556]: syntax error: unclosed tag \{if} (opened line 385). (Smarty_Compiler.class.php, line 317)
Произошла фатальная ошибка на строке 1094 в файле /var/www/data/www/bans.ru/includes/smarty/Smarty.class.php

11: /includes/smarty/Smarty.class.php::trigger_error('Smarty error: [in page_bans.tpl line 556]: syntax error: unclosed tag \{if} (opened line 385). (Smarty_Compiler.class.php, line 317)', 256) - 1094
10: /includes/smarty/Smarty.class.php::trigger_error('[in page_bans.tpl line 556]: syntax error: unclosed tag \{if} (opened line 385). (Smarty_Compiler.class.php, line 317)', 256) - 1816
9: /includes/smarty/Smarty_Compiler.class.php::_trigger_fatal_error('syntax error: unclosed tag \{if} (opened line 385).', 'page_bans.tpl', 556, '/var/www/data/www/bans.ru/includes/smarty/Smarty_Compiler.class.php', 317, 256) - 2256
8: /includes/smarty/Smarty_Compiler.class.php::_syntax_error('unclosed tag \{if} (opened line 385).', 256, '/var/www/data/www/bans.ru/includes/smarty/Smarty_Compiler.class.php', 317) - 317
7: /includes/smarty/Smarty.class.php::_compile_file('page_bans.tpl', ...', ) - 1490
6: /includes/smarty/Smarty.class.php::_compile_source('page_bans.tpl', ...', , '/var/www/data/www/bans.ru/themes_c//new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.inc') - 1423
5: /includes/smarty/Smarty.class.php::_compile_resource('page_bans.tpl', '/var/www/data/www/bans.ru/themes_c//new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php') - 1255
4: /includes/smarty/Smarty.class.php::fetch('page_bans.tpl', , 'new_box', 1) - 1107
3: /pages/page.banlist.php::display('page_bans.tpl') - 811
2: /includes/page-builder.php::include('/var/www/data/www/bans.ru/pages/page.banlist.php') - 136
1: /index.php::include_once('/var/www/data/www/bans.ru/includes/page-builder.php') - 35

**Comment by redbol** [comment]
Пофикшено.
