### ISSUE TITLE
Warning: Illegal string offset 'commenttxt'

### ISSUE THREAD

**Issue by RED4911** [CrazyHackGUT/SB_Material_Design#15]
arning: Illegal string offset 'commenttxt' in /var/www/data/www/bans.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 483
�

Warning: Illegal string offset 'editcomlink' in /var/www/data/www/bans.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 487

**Comment by redbol** [comment]
Почисть кеш в настройках сб и очисти таблицу "sb_comments" в бд СБ

**Comment by redbol** [comment]
И отпишись, нормализовалось ли :)

**Comment by RED4911** [comment]
Почистил везде. Все по прежнему осталось.

**Comment by RED4911** [comment]
Хотя сейчас я увидел что ты сделал чтоб сворачивалось. Вот вроде полный ошибки 
Warning: Illegal string offset 'editcomlink' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 494

Warning: Illegal string offset 'editcomlink' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 494
�

**Comment by redbol** [comment]
@RED4911, Ты качал эти файлы? http://puu.sh/s6o2A/f746960799.png Я там это вроде бы уже фиксил...

**Comment by redbol** [comment]
Еще пару фоксов засунул, перекачай эти файлы с гит(не с релизной версии) и закинь page.banlist.php в pages, а page_bans.tpl в themes/new_box/ с заменой.

**Comment by RED4911** [comment]
Стало еще больше ошибок 

`Warning: Illegal string offset 'edittime' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 480
редактировал
Warning: Illegal string offset 'editname' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 480

Warning: Illegal string offset 'editname' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 480
� в
Warning: Illegal string offset 'edittime' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 481
�	


Warning: Illegal string offset 'commenttxt' in /var/www/mixempire/data/www/bans.mixempire.ru/themes_c/new_box^%%AE^AE1^AE1080EF%%page_bans.tpl.php on line 483
�`

**Comment by redbol** [comment]
@CrazyHackGUT Выручай))

**Comment by CrazyHackGUT** [comment]
Сейчас посмотрим...

**Comment by CrazyHackGUT** [comment]
Исправлено. Кое-кто перевёл то, чего не следовало переводить. В итоге шаблонизатор ступорился и творил эту хрень.

**Comment by CrazyHackGUT** [comment]
Если проблема вдруг осталась, переоткрывайте Issue. Будем досконально пересматривать проблему.

**Comment by Meowmurmur** [comment]
Проблема осталась. И ещё вот такая фигня (где курсор) или это из-за ошибки?
![bandicam 2016-11-04 22-05-15-704](https://cloud.githubusercontent.com/assets/13346898/20020672/232cad2e-a2db-11e6-9236-b27fc63f11f4.jpg)

**Comment by CrazyHackGUT** [comment]
@Meowmurmur это из-за ошибки.
Ссылку на SourceBans. И желательно файл шаблона куда-нибудь загрузите. Просмотрю. Может, не обновили вы его таки :)

**Comment by Meowmurmur** [comment]
http://steampipe.ru/sourcebans/ (от лица не авторизованного пользователя всё норм)
http://pastebin.com/WGQZWgiW (Скачивал все файлы как-раз перед вашим фиксом)

**Comment by CrazyHackGUT** [comment]
`{if $ban.commentdata != "Нету"}`
У меня в фиксе прописано "Нет", а не "Нету" :laughing: 
Пробуй менять своё "Нету" на "Нет"

**Comment by Meowmurmur** [comment]
Ложная тревога, всё норм теперь :laughing:

**Comment by CrazyHackGUT** [comment]
Тогда Issue закрываю. Надеюсь, эта проблема решена раз и навсегда.
