### ISSUE TITLE
english

### ISSUE THREAD

**Issue by piotrekkrol7** [CrazyHackGUT/SB_Material_Design#17]
Hi this is nice but can you add english?

**Comment by CrazyHackGUT** [comment]
We're try to do this, but we do not promise :(

**Comment by piotrekkrol7** [comment]
Pleas this is awesome 👍  This is for you some time

**Comment by redbol** [comment]
you can report bugs. This content was established only under the Russian audience.
Ps, google translate

**Comment by CrazyHackGUT** [comment]
Once all of the planned changes will be made, we will add multilanguage and English.
I close this issue.
