### ISSUE TITLE
Не работает сохранение настроек.

### ISSUE THREAD

**Issue by romkazor** [CrazyHackGUT/SB_Material_Design#18]
В unstable версии (Версия 1.5.4.7 / 1.1.5 Not Stabled(In developing) (511)) не работает сохранение настроек со страницы index.php?p=admin&c=settings
При применении изменений все галочки и настройки сбрасываются к исходному виду.

**Comment by CrazyHackGUT** [comment]
На самом деле, всё сохраняется. Просто по неизвестной причине, при загрузке настроек, галочки обратно не устанавливаются.
Решить эту проблему планируется в ближайшие два-три дня.

**Comment by romkazor** [comment]
Ну не совсем. В итоге и галочек нет и пунктов которые я выбрал к примеру отображать в левом меню тоже нет

**Comment by CrazyHackGUT** [comment]
А, кажется я понял, что вы имеете в виду.
Нет, это не баг. Включая протест бана и тд., они автоматически в меню слева не добавятся. Их надо так же вручную включить в настройках SourceBans.
![Всё здесь](http://i.imgur.com/Nxv5CWH.png)

**Comment by romkazor** [comment]
Да, теперь появились если активировать еще и в меню. Но в любом случае галочки не сохраняются (это уже не так критично)

**Comment by CrazyHackGUT** [comment]
Исправлено. Будет в одном из коммитов завтра.
