### ISSUE TITLE
обновление (updater)

### ISSUE THREAD

**Issue by miki1966** [CrazyHackGUT/SB_Material_Design#20]
установка прошла нормально но при обновление выдает ошибку 
![2016-11-13_231716](https://cloud.githubusercontent.com/assets/23016396/20277513/54abd30c-aaba-11e6-9657-503b79a172e1.png)
![2016-11-14_212019](https://cloud.githubusercontent.com/assets/23016396/20277514/54af9d34-aaba-11e6-8f37-36159b9c3d4a.png)

**Comment by CrazyHackGUT** [comment]
Странные у вас ошибки. Ни стак трейсов, ни чего.
Было бы неплохо получить FTP-доступ к сайту. Посмотрю.
Естественно, это в ЛС.

**Comment by miki1966** [comment]
я вк написал

**Comment by CrazyHackGUT** [comment]
Проблема решена. Её и не было. Или она с первого раза не появляется.
