### ISSUE TITLE
Не сохряеться смена веб группы админа

### ISSUE THREAD

**Issue by rsgua** [CrazyHackGUT/SB_Material_Design#21]
Не сохряеться смена веб группы админа.

**Comment by redbol** [comment]
А вот эта проблема действительно есть, но я хочу узнать корень этой проблемы, группы вы переносили с старой сб?

**Comment by CrazyHackGUT** [comment]
Веб-группа не будет сохраняться, пока не будет установлен E-Mail и пароль для входа в веб-часть. Об этом должна вылезать ошибка, но она не вылезает по некоторым причинам :laughing: 
Исправлено будет сегодня вечером.

**Comment by CrazyHackGUT** [comment]
Исправил, вроде бы. Просьба установить фикс и отписаться.

**Comment by rsgua** [comment]
работает. еще осталься баг когда инфу меняешь и просит эмейл ввести но он ведь не обезательный...

**Comment by CrazyHackGUT** [comment]
E-Mail обязателен, если указывать веб-группу. Это не баг. Он требуется для "восстановления пароля", если администратор забыл его.

**Comment by rsgua** [comment]
в новом сб когда добавляешь админа он не обезательный. еще 1.4.9 такое было... возьми добавь админа и увидишь эмейл не нужен

**Comment by rsgua** [comment]
сейчас есть там вход через стим и эмейл стал не нужным и так же пароль. и так можна убрать это при активации ваучера.

**Comment by CrazyHackGUT** [comment]
Я сейчас создал для теста админа в своём бета-СБ и попытался отредактировать его, не указав ему веб-привилегии. Он прекрасно отредактировался.
Добавил фул доступ к вебу, попытался ещё раз "отредактировать" его из админпанели, ничего не меняя - затребовало E-Mail.

Так что не совсем ясно, что вы имели ввиду. Попробуйте донести.
Собсна, пруфы, что всё работает, как и задумано: https://www.dropbox.com/s/040o8l65xgx59fh/2016-11-24_23-36-47.mp4?dl=0

**Comment by rsgua** [comment]
я понимаю но для веб части не нужен эмейл и пароль. в новом сб сделали это не обезательным.
я добавил админ баз эмейла и пароля, а отредактировать его не могу без него.

**Comment by redbol** [comment]
Мыло и пасс обязательны. Если тебе эти поля не нужны, удаляй смело страницу авторизации и страницу восстановления пароля. То, что у тебя АВТОРИЗАЦИЯ через СТИМ, это не значит, что другим не надо входить в аккаунт по логину и пассу.

**Comment by rsgua** [comment]
ну да в стандартном сб+++ не обезательный эмейл так как можна зайти через стим и не надо востанавлевать пароль

**Comment by CrazyHackGUT** [comment]
Покажите на видео, что там E-Mail необязателен.

**Comment by CrazyHackGUT** [comment]
Т.к. проблема решена, а на доп. вопрос автор не отвечает, я вынужден закрыть Issue.
