### ISSUE TITLE
Не видно игроков в списку серверов

### ISSUE THREAD

**Issue by rsgua** [CrazyHackGUT/SB_Material_Design#22]
Не видно игроков в списку серверов. Игра кс:го

**Comment by CrazyHackGUT** [comment]
Неоднократно обсуждалось на HLMod. В CS:GO есть серверная переменная, которая блокирует отдачу списка игроков по протоколам движка. Отключите её, и игроки появятся.

Читайте [этот пост](http://hlmod.ru/threads/alpha-material-admin-refork-na-osnove-sb-1-5-4-7-bootstrap-3.36382/page-39#post-268894) и ещё три снизу.

**Comment by rsgua** [comment]
host_info_show 2
host_players_show 2
стоит и все равно не показывает

**Comment by CrazyHackGUT** [comment]
До последних обнов чего? Самой игры или SB?

**Comment by rsgua** [comment]
sb

**Comment by Meowmurmur** [comment]
Теперь нормально всё, но время игрока на сервере отображается чуть-чуть не так, 
нужно так - "48 Мин, 35 Сек", а пишет - "48:35"

**Comment by CrazyHackGUT** [comment]
@Meowmurmur сейчас исправлю
@rsgua да, косяк действительно был. Класс работы с серверами не был полностью перенесён в работоспособном режиме для СБ. Сейчас уже вроде всё.

**Comment by CrazyHackGUT** [comment]
Поправил.

**Comment by CrazyHackGUT** [comment]
Я так понял, что проблем больше не наблюдается с этим. Потому Issue закрываю.
Если снова возникнет - переоткрывайте.
