### ISSUE TITLE
AJAX Call Failed! при вводе в РКОНе комманды sm plugins list

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#23]
"Error: the XML response that was returned from the server is invalid."
Так как плагинов на сервере дохрена, окошко с ошибкой уходить за экран, но при этом страницу вниз нельзя пролистать.

**Comment by redbol** [comment]
Скрин бы)

**Comment by Meowmurmur** [comment]
![bandicam 2016-11-26 15-38-13-423](https://cloud.githubusercontent.com/assets/13346898/20640705/60ef02c8-b3ee-11e6-9fb3-5e3b24802005.jpg)

**Comment by CrazyHackGUT** [comment]
Такая проблема действительно присутствует. Порой сам на неё натыкаюсь. С чем связано - пока что самому не ясно. Как только будет информация, как это фиксить - исправлю и отпишусь.

**Comment by redbol** [comment]
Скорее всего дело либо в большом размере "получаемого пакета", либо то, что у тебя в ответе используются " - кавычки, может быть синтаксис нарушается... Что-то из этого. Попробуй потестить команды, на ответ которых будет текст с [ " ]- кавычками

**Comment by Meowmurmur** [comment]
Если hostname ввести, то всё нормально. (возможно не совсем ту команду выбрал для проверки)

**Comment by redbol** [comment]
Значит "получаемый пакет данных" слишком большой, там в сб было это учтено, но @CrazyHack же добавил другую серверную библиотеку xPaw, поэтому может быть и несостыковка)

**Comment by CrazyHackGUT** [comment]
Синтаксис не "бьётся", это проверено. Я хочу попробовать обновить XAJAX-библиотеку. В SourceBans она версии 0.2.5, когда уже есть 0.6

**Comment by CrazyHackGUT** [comment]
Это неисправимо. Ждём идей для фикса, пока что, от команды разработчиков SB++. На время - Issue прикрываю.

(хотя у них тоже нет идей, я читал их репозиторий)
