### ISSUE TITLE
Не правильное отображение времени выдачи мута/бана

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#25]
http://steampipe.ru/sourcebans/index.php?p=commslist
Для примера мут с ником "Test", пишет, что выдан в 23:01, а на самом деле в 21:01. Часовой пояс стоит GMT +3 (На форуме время нормально отображается).

**Comment by CrazyHackGUT** [comment]
Часовой пояс в настройках SourceBans правильно настроен?
![img](http://i.imgur.com/XFzU8KO.png)

**Comment by Meowmurmur** [comment]
Да, я же писал, что стоит GMT +3 :)

**Comment by CrazyHackGUT** [comment]
Кинь в ЛС где-нибудь данные от любого акка с доступом к настройкам. Потестим кое-что.
Можно в [ВК](https://vk.com/crazyhackgut), на [ХЛмоде](http://hlmod.ru/conversations/add?to=CrazyHackGUT) или в [Стиме](https://steamcommunity.com/profiles/76561198071596952/).

**Comment by CrazyHackGUT** [comment]
Проблема закрыта, т.к. оказалось, что время неправильно настроено на игровом сервере.
