### ISSUE TITLE
Баг при режиме отладки

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#28]
![bandicam 2016-12-11 01-16-10-146](https://cloud.githubusercontent.com/assets/13346898/21076865/a30782be-bf3f-11e6-91fd-d5a51227fd9c.jpg)
![bandicam 2016-12-11 01-16-15-140](https://cloud.githubusercontent.com/assets/13346898/21076872/c772b5ba-bf3f-11e6-95aa-b25f81043473.jpg)
Не знаю конечно, баг это или нет, но сообщить всё-таки решил)

**Comment by CrazyHackGUT** [comment]
Это не баг, а недоработка. Но если очень сильно мозолит глаза, могу доработать эту хрень.

**Comment by CrazyHackGUT** [comment]
![Верх режима отладки](http://i.imgur.com/Wq30PXb.png)
![Низ режима отладки](http://i.imgur.com/bzY9V8u.png)
