### ISSUE TITLE
Отсутствует картинка

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#3]
Путь: themes/new_box/images/admin/help.png 
Используется в системном логе.

**Comment by CrazyHackGUT** [comment]
К слову, это я её затёр)
Я не видел ни разу нигде, чтобы она использовалась, и затёр всю папку */themes/new_box/images/* в шаблоне с чистой душой :laughing:

**Comment by redbol** [comment]
Ну вот теперь понятно) А то файлы стали пропадать)
