### ISSUE TITLE
Новый плагин, можна выдать несколько банов или мутов одновременно

### ISSUE THREAD

**Issue by rsgua** [CrazyHackGUT/SB_Material_Design#30]
Новый плагин, можна выдать несколько банов или мутов одновременно

**Comment by Grey-rus** [comment]
в чём собственно вопрос то?

**Comment by rsgua** [comment]
забыл дописать на одного игрока

**Comment by Grey-rus** [comment]
// Возможность банить или мутить несколько человек за раз через меню, к консольным командам не относится
		"MassBan"			"1"
в конфиге (последняя версия).

**Comment by rsgua** [comment]
да ты не понял одного и того игрока можна замутить много раз

**Comment by Grey-rus** [comment]
Надо писать понятным языком, а то не понятно. Это так было задумано, типо обновление или продление.

**Comment by CrazyHackGUT** [comment]
Т.к. не является багом по уверению разработчика, Issue закрываю.
