### ISSUE TITLE
При бане через ВЕБ не получает IP

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#31]
![12345](https://cloud.githubusercontent.com/assets/13346898/21315172/7d5b292e-c603-11e6-90ac-258200cc26dd.jpg)
Собственно на скрине всё видно.

**Comment by CrazyHackGUT** [comment]
В процессе. Про проблему знаем.

**Comment by CrazyHackGUT** [comment]
Исправлено в dev-репозитории. См. коммиты #fc681b5 и #a04ed23
