### ISSUE TITLE
PHP 8.0.1

### ISSUE THREAD

**Issue by bubobih** [CrazyHackGUT/SB_Material_Design#315]
An exception occured: [Error] Undefined constant "INPUT_SESSION" in /init.php on line 315
include_once() in /index.php at line 37

**Comment by CrazyHackGUT** [comment]
This is already in WiP.

**Comment by inzanty** [comment]
UPD: I have been already created branch with version which will be compatible with PHP 7.4/8.0+. Soon you can use this version.

**Comment by inzanty** [comment]
Fixed.
