### ISSUE TITLE
Получение реального IP при использовании CloudFlare

### ISSUE THREAD

**Issue by lortboza** [CrazyHackGUT/SB_Material_Design#316]
При использовании CloudFlare сб выдает не реальный айпи, а айпи присвоенный CloudFlare.
![image](https://user-images.githubusercontent.com/37963273/109214423-7d9d1100-77ba-11eb-978f-a0908883c3f4.png)
![image](https://user-images.githubusercontent.com/37963273/109214540-a2918400-77ba-11eb-92b2-d4d6a908e556.png)

**Comment by West14** [comment]
Конфигурируйте сервер правильно, если nginx - гуглим `set_real_ip_from` и `real_ip_header` для cloudflare.
МА тут не при чём.

**Comment by BlackYuzia** [comment]
@West14 а если Веб хостинг, а не VDS?
Есть аналогичный способ через код: (не тестил правда)
![image](https://user-images.githubusercontent.com/25010528/109387363-b7c8f880-7909-11eb-907d-46682e465f61.png)

Источник: https://www.easycoding.org/2013/08/12/nastraivaem-probros-ip-klientov-za-cloudflare.html

**Comment by CrazyHackGUT** [comment]
> а если Веб хостинг

Писать в ТП. Я не вижу практического смысла запрягать пых этим.

**Comment by BlackYuzia** [comment]
Осуждаю. Ну ладно. Закрывай иссуйку.

**Comment by BlackYuzia** [comment]
Closed by "As designed".

Use this for resolve real IP from Cloudflare: https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-logging-visitor-IP-addresses
