### ISSUE TITLE
SourceSleuth

### ISSUE THREAD

**Issue by xeeek** [CrazyHackGUT/SB_Material_Design#317]
Есть идея доработать немного функцию SourceSleuth в ма. 
Сейчас если включить ее, то челики, ip который совпадает с каким либо баном, не смогут зайти на сервер. 
Какая проблема? Проблема, что есть вероятность (я таких поймал 2 за маленькое время), что ip может совпасть с человеком, которого забанило допустим 6 месяцев назад.
Идея для реализации такая, чтобы добавить время, за которое от текущей даты будут проверяться баны (Допустим 2 недели по стандарту). 
И точно не могу сказать, но вроде бан не перевыдаётся, а просто нельзя зайти, т.к. бан в бд уже есть. Добавить пункт "Перебанивать ли игрока, если ip совпал" , и время в тот же конфиг "2.0" (в 2 раза больше старого) например. Причину бана думаю можно брать старую, либо "Обход бана"

**Comment by megoRU** [comment]
Идея хорошая. Эх добавил работы крузи по миграции БД))
