### ISSUE TITLE
Импорт банов завершен, но баны не добавились в БД

### ISSUE THREAD

**Issue by Kailo97** [CrazyHackGUT/SB_Material_Design#318]
**Describe the bug**
Баны импортируются из файла banned_user.cfg полученного с другой панели. Сообщается о успешном импорте и указывается верное количество, но список банов не изменяется.
В `pages/admin.bans.php` был добавлен `error_reporting(E_ALL);` и по итогу получено следующее сообщение о ошибке
```
[256] mysqli error: [1048: Column 'aid' cannot be null] in EXECUTE("INSERT INTO sb_bans(created,authid,ip,name,ends,length,reason,aid,adminIp,type) VALUES (UNIX_TIMESTAMP(),'STEAM_0:0:81591455','','Импортированный бан',(UNIX_TIMESTAMP() + 0),0,'Импорт из banned_user.cfg',NULL,'178.219.46.164','0')")
```
Очевидно что `$_COOKIE['aid']` вернул `NULL`. Для теста перелогинился (используется авторизация по имени пользователя и паролю). Список cookie содержит лишь одну запись вида `a_15453` (пишу название на память, может отличатся).

**To Reproduce**
1. Открыть панель управления банов.
2. Вкладку импорта банов.
3. Выполнить импорт.
4. Проверить список банов.

**Expected behavior**
Баны импортированы.

**Desktop (please complete the following information):**
 - Версия 1.1.6 (526)

**Comment by CrazyHackGUT** [comment]
Теперь должно быть исправлено. Локально проверил - всё импортируется.
