### ISSUE TITLE
[Баг] Редирект после steam_auth.php

### ISSUE THREAD

**Issue by MAGNAT2645** [CrazyHackGUT/SB_Material_Design#319]
Если используется поддомен (например, `sb.example.com`), то после авторизации клиента кидает на `example.com/steam_auth.php`, выдавая 404.
Т.е. поддомен не учитывается/запоминается.

Неверная ссылка появляется ещё в запросе, ключ `open_id.return_to`.
Возможно, это баг на стороне OpenID, а не сам SB.

**Comment by CrazyHackGUT** [comment]
А ссылка с протоколом прописана в конфиге или нет?
У меня у самого MA стоял очень долгое время на поддомене (`bans.example.com`), и всё прекрасно работало.

**Comment by MAGNAT2645** [comment]
Ой. А ведь я действительно забыл указать поддомен в `SB_WP_URL` :smile:
Спасибо за быстрый ответ.
