### ISSUE TITLE
Репозиторий МОДов: идеи, пожелания, etc.

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#32]
В файлах вроде есть иконка в стиле material, но используется старая.

**Comment by CrazyHackGUT** [comment]
В одной из новых версий будет введена такая вещь, как "Репозиторий МОДов". По умолчанию, SourceBans будет поставляться без МОДов, но их можно будет установить с иконками и картинками карт из репозитория.
В данный момент, весь код готов в тестовом режиме, но пока что никто не хочет помогать с картинками карт для СБ :(

**Comment by Meowmurmur** [comment]
Для каких игр скриншоты карт в большем приоритете? Готов помочь ;)

**Comment by CrazyHackGUT** [comment]
Тех, которых у меня нет :wink:
- *Day of Defeat: Source*
- *Insurgency: Source*
- *Dystopia*
- *Hidden: Source*
- *Half-Life 2: Capture the Flag*
- *Pirates Vikings and Knights II*
- *Perfect Dark: Source*
- *Zombie Panic*
- *Left 4 Dead* (она у меня есть, но свободное место на винчестере не позволяет её скачать)
- *CSPromod*
- *Alien Swarm*
- *E.Y.E: Divine Cybermancy*
- *Nuclear Dawn*
- *No More Room in Hell*

**Comment by Meowmurmur** [comment]
Для обеих КС могу попробовать предоставить, исходя из моих маплистов. На счёт l4d и тф2 не уверен. Об остальных играх ниразу не слышал, так что сложновато будет для их карт скриншоты искать.
И ещё такой вопрос по поводу скринов карт, я думаю вы знаете, что у некоторых карт есть куча версий, так вот, эта система будет брать скриншот только по основной части названия карты или только по полному названию? тк постоянно редактировать название скрина/кидать новый слишком геморно.

**Comment by CrazyHackGUT** [comment]
По ТФ я предоставлю сам. У меня ещё свои картинки есть для кастома, хочу ими поделиться ;)
По полному названию. Ничто не мешает в случае чего скопировать скрин под именем другой версии, если там мало отличий.

**Comment by Meowmurmur** [comment]
Дабы не создавать новый issue, напишу сюда. Последний удаленный мод, на вкладке установить из репозитория отмечен как установлен. Это побочный эффект того, что это ещё не доступно?

**Comment by CrazyHackGUT** [comment]
Сейчас обновлю свой бета SourceBans, проверю и отпишу...

**Comment by CrazyHackGUT** [comment]
Покажите скриншотом.

**Comment by Meowmurmur** [comment]
![screenshot_2016-12-20-14-13-04](https://cloud.githubusercontent.com/assets/13346898/21350147/82bf86d8-c6be-11e6-87bb-810393daa42c.png)
![screenshot_2016-12-20-14-13-15](https://cloud.githubusercontent.com/assets/13346898/21350149/88881184-c6be-11e6-9943-8ef7a66c7942.png)

**Comment by CrazyHackGUT** [comment]
Почему кол-во модов 2, а отображается только 1?
Дамп таблицы `sb_mods` в студию.

**Comment by Meowmurmur** [comment]
http://rgho.st/88cHDKxSN

**Comment by CrazyHackGUT** [comment]
Скинь в ЛС куда-нибудь данные доступа к веб-морде СБ с линком на него. Или просто линк, но добавь админа: **STEAM_0:0:55665612**

**Comment by Alleksandr-Bel** [comment]
Проблема, бан или мут через веб выдаются на всех серверах и в графе сервер всегда пишет: Пожалуйста, подождите... Как это можно исправить?

**Comment by CrazyHackGUT** [comment]
В логах ошибок PHP что-нибудь есть? И для этого надо было отдельный Issue создавать.

**Comment by CrazyHackGUT** [comment]
Увы, идея отправлена в "чёрную коробку". Хочется верить, что всё таки в каком-нибудь другом, похожем проекте, она будет реализована.
