### ISSUE TITLE
Remove or Disable Servers Rcon Auto Deleting 

### ISSUE THREAD

**Issue by BlackYuzia** [CrazyHackGUT/SB_Material_Design#323]
@CrazyHackGUT from 2018 year this trouble is exist. Remove auto delete rcon by default or add settings (simple - in config file) for disable that.

#138

@CrazyHackGUT cock or yes?

**Comment by CrazyHackGUT** [comment]
Duplicate.

**Comment by BlackYuzia** [comment]
ПИДОРАС
