### ISSUE TITLE
[BUG] Администратор снят в истекших банах

### ISSUE THREAD

**Issue by BlackYuzia** [CrazyHackGUT/SB_Material_Design#324]
В случае если бан истекает, админ (который снял бан) в этом бане указывается как "Администратор снят". Что не есть правильно.

![image](https://user-images.githubusercontent.com/25010528/144428081-aa8f8e5f-7e01-46b8-92ad-42d5f2934066.png)
![image](https://user-images.githubusercontent.com/25010528/144428121-84e6d0d8-147d-4f73-b081-61457f3cd6aa.png)

**Comment by CrazyHackGUT** [comment]
Can be checked here: https://material.kruzya.me/index.php?p=banlist
