### ISSUE TITLE
[BUG] Show Console Instead of Admin

### ISSUE THREAD

**Issue by BlackYuzia** [CrazyHackGUT/SB_Material_Design#330]
### Description

В базе указано что админ забанил, хотя выводится будто бы  консоль.

![image](https://user-images.githubusercontent.com/25010528/151710817-9a1d216e-fba6-4a17-a8b9-e6f94962ac7b.png)
![image](https://user-images.githubusercontent.com/25010528/151710854-5fc1df61-7491-4918-9ea3-a436e883c026.png)

**Comment by CrazyHackGUT** [comment]
![изображение](https://user-images.githubusercontent.com/12576822/151711104-8e4c85f0-3ca6-4f20-a5ad-dd81b564e503.png)
В чём вопрос? Я вижу админа "0"

**Comment by CrazyHackGUT** [comment]
Не удаётся воспроизвести локально.
