### ISSUE TITLE
Возможность удаления бана без прав на удаление

### ISSUE THREAD

**Issue by rm-veil** [CrazyHackGUT/SB_Material_Design#334]
Баг позволяет без следов удалить любой действующий бан. Для этого администратору нужны всего лишь права на изменения банов

Для воспроизведения бага нужно
1. Зайти в список банов
2. Нажать "Редактировать" на любом действующем бане
3. В поле "Тип бана" выбрать "IP адрес"
4. В поле "Steam ID / Community ID" убрать все символы
5. В поле IP адрес ввести любое поддерживаемое SB значение IP например 127.0.0.1
6. Нажать "Сохранить" 
P.S. Другие поля не влияют на результат.

В результате проделанных операций бан полностью удаляется как с веб части так и соответственно с базы данных. Причём были проведены тесты в результате которых мы узнали о том, что след от выданного бана полностью удаляется, как будто бана вовсе не было.

![IMG_20220414_121051](https://user-images.githubusercontent.com/91317574/163354000-3d628fbd-a3eb-4754-898b-c7edb7ed914b.jpg)
![IMG_20220414_121147](https://user-images.githubusercontent.com/91317574/163354005-a9a12395-daf8-443f-8d26-9bdfe6a28b1d.jpg)
![IMG_20220414_121341](https://user-images.githubusercontent.com/91317574/163353987-dd8c3430-8be4-43a2-aeea-217127d8246c.jpg)
![IMG_20220414_121423](https://user-images.githubusercontent.com/91317574/163353996-30a0d996-261c-490e-93fb-be58583073b7.jpg)

 - OS: Windows, Android, etc.
 - Browser: Chrome, FireFox, etc.
 - Version: Any

**Comment by CrazyHackGUT** [comment]
Прикольный баг. Бан не удаляется в ходе редактирования на самом деле. Он удаляется позже регламентной процедурой, которая чистит все баны с невалидным стимом.

**Comment by CrazyHackGUT** [comment]
Добавил условие на тип бана: если тип бана IP, то оно трогать его не будет при невалидном Стиме.
