### ISSUE TITLE
При нажатии кнопки "редактировать" группу, "вкладка" разворачивается

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#34]
И ещё группы веб админов выделены жирным, хотя группы серверных админов нет.

**Comment by CrazyHackGUT** [comment]
1). Срабатывает стандартный эвент. Всё в порядке, так и должно быть. Точно так же и на любой другой странице. Я костылить ради такой мелочи, которая присутствует даже в оригинальном шаблоне SourceBans, не буду.
2). Сам знаю, и не знаю, почему. Тега ожирнения нигде нет, как и стиля. Разбираюсь, пока что.

**Comment by CrazyHackGUT** [comment]
Решил. Весь прикол был в вёрстке. Использовался `<th>` вместо `<td>`.
