### ISSUE TITLE
Permission to change expired bans/comms

### ISSUE THREAD

**Issue by rm-veil** [CrazyHackGUT/SB_Material_Design#349]
По идеи если бан/мут/гаг истёк, не должно быть права на его изменение, т.к. соответствующей кнопки на истёкшем наказании нет, но если использовать ссылку для редактирования бана/мута/гага можно изменять и истёкшие наказания.

**To Reproduce**

1. Находим айди наказания, которое хотим изменить
_Для этого инспектором кода можно нажать на чекбокс возле наказания и найти айди_
`<input type="checkbox" name="chkb_0" id="chkb_0" value="181574" hidden="hidden">`
2. Используя ссылку для редактирования (значение key разное, актуальную ссылку можно получить нажав на Редактировать в действующем наказании) `https://example.com/index.php?p=admin&c=bans&o=edit&id=181574&key=some.value` изменяем id на айди истёкшего наказания и прожимаем Enter.

Открывается страница с редактированием уже истёкшего наказания, после сохранения все изменения сохраняются без потерь. Можно изменить любое значение поля.
Проведенные тесты:
1. Если у истёкшего наказания изменить срок, наказание всё равно будет истёкшим, но уже с новым значением срока
![image](https://user-images.githubusercontent.com/91317574/186662402-f3d217f5-0412-434c-aadd-99a0897eca4a.png)
2. Если у истёкшего наказания изменить steamid, то игрок с steamid вставленным в истёкшее наказание будет иметь доступ к серверу

 - Version 1.1.6 (527)

**Comment by CrazyHackGUT** [comment]
Поправил, добавил проверку на снятость бана/мута либо его истечение.
