### ISSUE TITLE
При выдаче бана через веб некоторые символы в никах не отображаются

### ISSUE THREAD

**Issue by rm-veil** [CrazyHackGUT/SB_Material_Design#354]
Если выдать бан из-под сервера игроку с ником содержащим "<3", то в вебе ник отображается корректно. Но если выдать бан через веб, вместо ника будет "имя игрока не указано". Так же если изменить бан выданный из-под сервера, то после изменения ник так же пропадёт.
![image](https://user-images.githubusercontent.com/91317574/189332203-c4fddbc7-37b7-4c40-800f-2173772c01f1.png)

 - Version 1.1.6 (527)

**Comment by CrazyHackGUT** [comment]
Поправил. На стороне бэка был стрип HTML-тегов, убрал его, учитывая, что вроде бы везде никнейм сейчас экранируется перед выводом.
