### ISSUE TITLE
Ошибка в переводе "подробностей бана" или так и должно быть?

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#36]
![bandicam 2016-12-22 14-27-05-294](https://cloud.githubusercontent.com/assets/13346898/21425602/cf532fb4-c852-11e6-9776-ded509b5a685.jpg)
Бан по IP.  Мне кажется правильно было бы "Ник/SteamID/IP не указан", но никак не "скрыт". Ну и не "Блокировку выдал", а "Бан выдал".

**Comment by CrazyHackGUT** [comment]
Поправим вечером.
