### ISSUE TITLE
Заявки на бан считает как аппеляции

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#37]
![bandicam 2016-12-22 20-42-23-972](https://cloud.githubusercontent.com/assets/13346898/21436455/39f7ff50-c887-11e6-9cd7-8a80cb124246.jpg)
![bandicam 2016-12-22 20-42-19-050](https://cloud.githubusercontent.com/assets/13346898/21436456/3c5c020a-c887-11e6-88c2-bdda367a7998.jpg)
![bandicam 2016-12-22 20-43-12-303](https://cloud.githubusercontent.com/assets/13346898/21436461/4b03a47a-c887-11e6-8d88-30f3f770cdef.jpg)

**Comment by CrazyHackGUT** [comment]
Эм, что не так? Заявка на бан находится в заявках на бан.

**Comment by tallanvor** [comment]
Видимо, больше к переводу претензии))
Апелляция - это ж обжалование :)

2016-12-22 21:05 GMT+02:00 Kruzya <notifications@github.com>:

**Comment by CrazyHackGUT** [comment]
Только всмотрелся в скриншоты. Понял, в чём ошибка. Исправлю.

**Comment by CrazyHackGUT** [comment]
Исправлено.
