### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by vBDSK** [CrazyHackGUT/SB_Material_Design#40]
L 12/26/2016 - 15:50:56: SourceMod error session started
L 12/26/2016 - 15:50:56: Info (map "surf_10x_reloaded") (file "errors_20161226.log")
L 12/26/2016 - 15:50:56: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:50:56: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:50:56: [SM] Call stack trace:
L 12/26/2016 - 15:50:56: [SM]   [0] Database.SetCharset
L 12/26/2016 - 15:50:56: [SM]   [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:50:56: [SM]   [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:51:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:51:26: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:51:26: [SM] Call stack trace:
L 12/26/2016 - 15:51:26: [SM]   [0] Database.SetCharset
L 12/26/2016 - 15:51:26: [SM]   [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:51:26: [SM]   [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:52:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:52:45: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:52:45: [SM] Call stack trace:
L 12/26/2016 - 15:52:45: [SM]   [0] Database.SetCharset
L 12/26/2016 - 15:52:45: [SM]   [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:52:45: [SM]   [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:53:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:53:00: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:53:00: [SM] Call stack trace:
L 12/26/2016 - 15:53:00: [SM]   [0] Database.SetCharset
L 12/26/2016 - 15:53:00: [SM]   [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:53:00: [SM]   [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:53:39: Error log file session closed.

**Comment by vBDSK** [comment]
12/26/2016 - 15:58:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:58:47: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:58:47: [SM] Call stack trace:
L 12/26/2016 - 15:58:47: [SM]   [0] Database.SetCharset
L 12/26/2016 - 15:58:47: [SM]   [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:58:47: [SM]   [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:58:47: rcon from "78.46.33.10:46086": command "ma_wb_rehashadm

**Comment by vBDSK** [comment]
Через web панель добавил серверные разрешения и доступ к серверу себе

**Comment by vBDSK** [comment]
В админку на сервере зайти не могу

**Comment by vBDSK** [comment]
L 12/26/2016 - 16:08:03: [new_sb/materialadmin.smx] map start ConnectBd
L 12/26/2016 - 16:08:04: [new_sb/materialadmin.smx] map start ConnectBd: yes
L 12/26/2016 - 16:08:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 16:08:04: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 16:08:04: [SM] Call stack trace:
L 12/26/2016 - 16:08:04: [SM]   [0] Database.SetCharset
L 12/26/2016 - 16:08:04: [SM]   [1] Line 1208, materialadmin/database.sp::OverridesDone

**Comment by CrazyHackGUT** [comment]
Блин, по серверной части пишите в этот Issue #26 
Не создавайте новые.

По поводу ошибки, я посмотрю.

**Comment by Grey-rus** [comment]
Пусть перекачает плагин, старая версия.

**Comment by CrazyHackGUT** [comment]
Исправлено, однако. Потому закрываю.
