### ISSUE TITLE
Лимит соединений к базе

### ISSUE THREAD

**Issue by x3m77rus** [CrazyHackGUT/SB_Material_Design#41]
mysql> mysql> show processlist;
+------+------+-----------+------+---------+-------+----------+------------------+
| Id   | User | Host      | db   | Command | Time  | State    | Info             |
+------+------+-----------+------+---------+-------+----------+------------------+
| 2207 | ---- | localhost | bans | Sleep   | 19139 |          | NULL             |
| 2208 | ---- | localhost | bans | Sleep   | 19079 |          | NULL             |
| 2209 | ---- | localhost | bans | Sleep   | 19019 |          | NULL             |
| 2210 | ---- | localhost | bans | Sleep   | 18959 |          | NULL             |
| 2211 | ---- | localhost | bans | Sleep   | 18899 |          | NULL             |
| 2212 | ---- | localhost | bans | Sleep   | 18839 |          | NULL             |
| 2214 | ---- | localhost | bans | Sleep   | 18779 |          | NULL             |
| 2215 | ---- | localhost | bans | Sleep   | 18718 |          | NULL             |
| 2216 | ---- | localhost | bans | Sleep   | 18658 |          | NULL             |
| 2217 | ---- | localhost | bans | Sleep   | 18564 |          | NULL             |
| 2219 | ---- | localhost | bans | Sleep   | 18538 |          | NULL             |
| 2220 | ---- | localhost | bans | Sleep   | 18478 |          | NULL             |
| 2221 | ---- | localhost | bans | Sleep   | 18418 |          | NULL             |
| 2222 | ---- | localhost | bans | Sleep   | 18358 |          | NULL             |
| 2223 | ---- | localhost | bans | Sleep   | 18298 |          | NULL             |
| 2224 | ---- | localhost | bans | Sleep   | 18238 |          | NULL             |
| 2225 | ---- | localhost | bans | Sleep   | 18163 |          | NULL             |
| 2226 | ---- | localhost | bans | Sleep   | 18059 |          | NULL             |
| 2227 | ---- | localhost | bans | Sleep   | 18057 |          | NULL             |
| 2228 | ---- | localhost | bans | Sleep   | 17997 |          | NULL             |
| 2229 | ---- | localhost | bans | Sleep   | 17937 |          | NULL             |
| 2231 | ---- | localhost | bans | Sleep   | 17815 |          | NULL             |
| 2232 | ---- | localhost | bans | Sleep   | 17803 |          | NULL             |
| 2233 | ---- | localhost | bans | Sleep   | 17743 |          | NULL             |
| 2234 | ---- | localhost | bans | Sleep   | 17683 |          | NULL             |
| 2235 | ---- | localhost | bans | Sleep   | 17623 |          | NULL             |
| 2236 | ---- | localhost | bans | Sleep   | 17563 |          | NULL             |
| 2237 | ---- | localhost | bans | Sleep   | 17503 |          | NULL             |
| 2238 | ---- | localhost | bans | Sleep   | 17443 |          | NULL             |
| 2239 | ---- | localhost | bans | Sleep   | 17383 |          | NULL             |
| 2240 | ---- | localhost | bans | Sleep   | 17322 |          | NULL             |
| 2241 | ---- | localhost | bans | Sleep   | 17251 |          | NULL             |
| 2242 | ---- | localhost | bans | Sleep   | 17202 |          | NULL             |
| 2243 | ---- | localhost | bans | Sleep   | 17142 |          | NULL             |
| 2245 | ---- | localhost | bans | Sleep   | 17069 |          | NULL             |
| 2246 | ---- | localhost | bans | Sleep   | 17009 |          | NULL             |
| 2247 | ---- | localhost | bans | Sleep   | 16949 |          | NULL             |
| 2248 | ---- | localhost | bans | Sleep   | 16889 |          | NULL             |
| 2249 | ---- | localhost | bans | Sleep   | 16829 |          | NULL             |
| 2250 | ---- | localhost | bans | Sleep   | 16769 |          | NULL             |
| 2251 | ---- | localhost | bans | Sleep   | 16709 |          | NULL             |
| 2252 | ---- | localhost | bans | Sleep   | 16649 |          | NULL             |
| 2253 | ---- | localhost | bans | Sleep   | 16588 |          | NULL             |
| 2254 | ---- | localhost | bans | Sleep   | 16528 |          | NULL             |
| 2255 | ---- | localhost | bans | Sleep   | 16468 |          | NULL             |
| 2256 | ---- | localhost | bans | Sleep   | 16408 |          | NULL             |
| 2257 | ---- | localhost | bans | Sleep   | 16348 |          | NULL             |
| 2259 | ---- | localhost | bans | Sleep   | 16288 |          | NULL             |
| 2260 | ---- | localhost | bans | Sleep   | 16214 |          | NULL             |
| 2261 | ---- | localhost | bans | Sleep   | 16196 |          | NULL             |
| 2262 | ---- | localhost | bans | Sleep   | 16136 |          | NULL             |
| 2264 | ---- | localhost | bans | Sleep   | 16016 |          | NULL             |
| 2265 | ---- | localhost | bans | Sleep   | 15956 |          | NULL             |
| 2266 | ---- | localhost | bans | Sleep   | 15896 |          | NULL             |
| 2267 | ---- | localhost | bans | Sleep   | 15836 |          | NULL             |
| 2268 | ---- | localhost | bans | Sleep   | 15776 |          | NULL             |
| 2269 | ---- | localhost | bans | Sleep   | 15715 |          | NULL             |
| 2270 | ---- | localhost | bans | Sleep   | 15655 |          | NULL             |
| 2271 | ---- | localhost | bans | Sleep   | 15595 |          | NULL             |
| 2272 | ---- | localhost | bans | Sleep   | 15535 |          | NULL             |
| 2273 | ---- | localhost | bans | Sleep   | 15475 |          | NULL             |
| 2274 | ---- | localhost | bans | Sleep   | 15415 |          | NULL             |
| 2275 | ---- | localhost | bans | Sleep   | 15355 |          | NULL             |
| 2276 | ---- | localhost | bans | Sleep   | 15295 |          | NULL             |
| 2277 | ---- | localhost | bans | Sleep   | 15278 |          | NULL             |
| 2279 | ---- | localhost | bans | Sleep   | 15158 |          | NULL             |
| 2280 | ---- | localhost | bans | Sleep   | 15098 |          | NULL             |
| 2281 | ---- | localhost | bans | Sleep   | 15038 |          | NULL             |
| 2282 | ---- | localhost | bans | Sleep   | 14978 |          | NULL             |
| 2283 | ---- | localhost | bans | Sleep   | 14918 |          | NULL             |
| 2284 | ---- | localhost | bans | Sleep   | 14858 |          | NULL             |
| 2285 | ---- | localhost | bans | Sleep   | 14758 |          | NULL             |
| 2286 | ---- | localhost | bans | Sleep   | 14738 |          | NULL             |
| 2287 | ---- | localhost | bans | Sleep   | 14677 |          | NULL             |
| 2288 | ---- | localhost | bans | Sleep   | 14617 |          | NULL             |
| 2289 | ---- | localhost | bans | Sleep   | 14557 |          | NULL             |
| 2290 | ---- | localhost | bans | Sleep   | 14497 |          | NULL             |
| 2291 | ---- | localhost | bans | Sleep   | 14437 |          | NULL             |
| 2292 | ---- | localhost | bans | Sleep   | 14377 |          | NULL             |
| 2293 | ---- | localhost | bans | Sleep   | 14317 |          | NULL             |
| 2294 | ---- | localhost | bans | Sleep   | 14257 |          | NULL             |
| 2295 | ---- | localhost | bans | Sleep   | 14197 |          | NULL             |
| 2296 | ---- | localhost | bans | Sleep   | 14137 |          | NULL             |
| 2297 | ---- | localhost | bans | Sleep   | 14076 |          | NULL             |
| 2298 | ---- | localhost | bans | Sleep   | 14016 |          | NULL             |
| 2299 | ---- | localhost | bans | Sleep   | 13956 |          | NULL             |
| 2300 | ---- | localhost | bans | Sleep   | 13896 |          | NULL             |
| 2301 | ---- | localhost | bans | Sleep   | 13836 |          | NULL             |
| 2302 | ---- | localhost | bans | Sleep   | 13776 |          | NULL             |
| 2303 | ---- | localhost | bans | Sleep   | 13716 |          | NULL             |
| 2304 | ---- | localhost | bans | Sleep   | 13656 |          | NULL             |
| 2305 | ---- | localhost | bans | Sleep   | 13596 |          | NULL             |
| 2307 | ---- | localhost | bans | Sleep   | 13536 |          | NULL             |
| 2308 | ---- | localhost | bans | Sleep   | 13475 |          | NULL             |
| 2309 | ---- | localhost | bans | Sleep   | 13415 |          | NULL             |
| 2310 | ---- | localhost | bans | Sleep   | 13355 |          | NULL             |
| 2311 | ---- | localhost | bans | Sleep   | 13295 |          | NULL             |
| 2312 | ---- | localhost | bans | Sleep   | 13235 |          | NULL             |
| 2313 | ---- | localhost | bans | Sleep   | 13175 |          | NULL             |
| 2314 | ---- | localhost | bans | Sleep   | 13115 |          | NULL             |
| 2315 | ---- | localhost | bans | Sleep   | 13055 |          | NULL             |
| 2316 | ---- | localhost | bans | Sleep   | 12995 |          | NULL             |
| 2317 | ---- | localhost | bans | Sleep   | 12935 |          | NULL             |
| 2318 | ---- | localhost | bans | Sleep   | 12874 |          | NULL             |
| 2319 | ---- | localhost | bans | Sleep   | 12814 |          | NULL             |
| 2320 | ---- | localhost | bans | Sleep   | 12754 |          | NULL             |
| 2321 | ---- | localhost | bans | Sleep   | 12694 |          | NULL             |
| 2322 | ---- | localhost | bans | Sleep   | 12634 |          | NULL             |
| 2323 | ---- | localhost | bans | Sleep   | 12574 |          | NULL             |
| 2324 | ---- | localhost | bans | Sleep   | 12514 |          | NULL             |
| 2325 | ---- | localhost | bans | Sleep   | 12454 |          | NULL             |
| 2326 | ---- | localhost | bans | Sleep   | 12394 |          | NULL             |
| 2327 | ---- | localhost | bans | Sleep   | 12280 |          | NULL             |
| 2328 | ---- | localhost | bans | Sleep   | 12273 |          | NULL             |
| 2329 | ---- | localhost | bans | Sleep   | 12213 |          | NULL             |
| 2330 | ---- | localhost | bans | Sleep   | 12153 |          | NULL             |
| 2331 | ---- | localhost | bans | Sleep   | 12093 |          | NULL             |
| 2332 | ---- | localhost | bans | Sleep   | 12033 |          | NULL             |
| 2333 | ---- | localhost | bans | Sleep   | 11973 |          | NULL             |
| 2334 | ---- | localhost | bans | Sleep   | 11913 |          | NULL             |
| 2335 | ---- | localhost | bans | Sleep   | 11853 |          | NULL             |
| 2336 | ---- | localhost | bans | Sleep   | 11793 |          | NULL             |
| 2337 | ---- | localhost | bans | Sleep   | 11733 |          | NULL             |
| 2338 | ---- | localhost | bans | Sleep   | 11672 |          | NULL             |
| 2339 | ---- | localhost | bans | Sleep   | 11612 |          | NULL             |
| 2340 | ---- | localhost | bans | Sleep   | 11552 |          | NULL             |
| 2341 | ---- | localhost | bans | Sleep   | 11492 |          | NULL             |
| 2342 | ---- | localhost | bans | Sleep   | 11432 |          | NULL             |
| 2358 | ---- | localhost | bans | Sleep   | 11372 |          | NULL             |
| 2359 | ---- | localhost | bans | Sleep   | 11312 |          | NULL             |
| 2360 | ---- | localhost | bans | Sleep   | 11252 |          | NULL             |
| 2361 | ---- | localhost | bans | Sleep   | 11192 |          | NULL             |
| 2362 | ---- | localhost | bans | Sleep   | 11132 |          | NULL             |
| 2363 | ---- | localhost | bans | Sleep   | 11071 |          | NULL             |
| 2364 | ---- | localhost | bans | Sleep   | 11011 |          | NULL             |
| 2365 | ---- | localhost | bans | Sleep   | 10951 |          | NULL             |
| 2366 | ---- | localhost | bans | Sleep   | 10891 |          | NULL             |
| 2367 | ---- | localhost | bans | Sleep   | 10831 |          | NULL             |
| 2369 | ---- | localhost | bans | Sleep   | 10771 |          | NULL             |
| 2370 | ---- | localhost | bans | Sleep   | 10711 |          | NULL             |
| 2371 | ---- | localhost | bans | Sleep   | 10651 |          | NULL             |
| 2372 | ---- | localhost | bans | Sleep   | 10591 |          | NULL             |
| 2373 | ---- | localhost | bans | Sleep   | 10531 |          | NULL             |
| 2374 | ---- | localhost | bans | Sleep   | 10470 |          | NULL             |
| 2375 | ---- | localhost | bans | Sleep   | 10388 |          | NULL             |
| 2376 | ---- | localhost | bans | Sleep   | 10350 |          | NULL             |
| 2377 | ---- | localhost | bans | Sleep   | 10290 |          | NULL             |
| 2379 | ---- | localhost | bans | Sleep   | 10230 |          | NULL             |
| 2380 | ---- | localhost | bans | Sleep   | 10170 |          | NULL             |
| 2381 | ---- | localhost | bans | Sleep   | 10110 |          | NULL             |
| 2382 | ---- | localhost | bans | Sleep   | 10050 |          | NULL             |
| 2383 | ---- | localhost | bans | Sleep   |  9990 |          | NULL             |
| 2384 | ---- | localhost | bans | Sleep   |  9930 |          | NULL             |
| 2385 | ---- | localhost | bans | Sleep   |  9869 |          | NULL             |
| 2386 | ---- | localhost | bans | Sleep   |  9809 |          | NULL             |
| 2387 | ---- | localhost | bans | Sleep   |  9749 |          | NULL             |
| 2388 | ---- | localhost | bans | Sleep   |  9689 |          | NULL             |
| 2389 | ---- | localhost | bans | Sleep   |  9629 |          | NULL             |
| 2390 | ---- | localhost | bans | Sleep   |  9569 |          | NULL             |
| 2391 | ---- | localhost | bans | Sleep   |  9509 |          | NULL             |
| 2392 | ---- | localhost | bans | Sleep   |  9449 |          | NULL             |
| 2393 | ---- | localhost | bans | Sleep   |  9389 |          | NULL             |
| 2394 | ---- | localhost | bans | Sleep   |  9329 |          | NULL             |
| 2395 | ---- | localhost | bans | Sleep   |  9268 |          | NULL             |
| 2396 | ---- | localhost | bans | Sleep   |  9208 |          | NULL             |
| 2397 | ---- | localhost | bans | Sleep   |  9148 |          | NULL             |
| 2398 | ---- | localhost | bans | Sleep   |  9088 |          | NULL             |
| 2399 | ---- | localhost | bans | Sleep   |  9028 |          | NULL             |
| 2401 | ---- | localhost | bans | Sleep   |  8968 |          | NULL             |
| 2402 | ---- | localhost | bans | Sleep   |  8908 |          | NULL             |
| 2403 | ---- | localhost | bans | Sleep   |  8848 |          | NULL             |
| 2408 | ---- | localhost | bans | Sleep   |  8788 |          | NULL             |
| 2409 | ---- | localhost | bans | Sleep   |  8728 |          | NULL             |
| 2410 | ---- | localhost | bans | Sleep   |  8667 |          | NULL             |
| 2411 | ---- | localhost | bans | Sleep   |  8607 |          | NULL             |
| 2412 | ---- | localhost | bans | Sleep   |  8547 |          | NULL             |
| 2413 | ---- | localhost | bans | Sleep   |  8487 |          | NULL             |
| 2414 | ---- | localhost | bans | Sleep   |  8427 |          | NULL             |
| 2415 | ---- | localhost | bans | Sleep   |  8367 |          | NULL             |
| 2416 | ---- | localhost | bans | Sleep   |  8307 |          | NULL             |
| 2417 | ---- | localhost | bans | Sleep   |  8247 |          | NULL             |
| 2418 | ---- | localhost | bans | Sleep   |  8187 |          | NULL             |
| 2419 | ---- | localhost | bans | Sleep   |  8127 |          | NULL             |
| 2420 | ---- | localhost | bans | Sleep   |  8066 |          | NULL             |
| 2421 | ---- | localhost | bans | Sleep   |  8006 |          | NULL             |
| 2422 | ---- | localhost | bans | Sleep   |  7946 |          | NULL             |
| 2423 | ---- | localhost | bans | Sleep   |  7886 |          | NULL             |
| 2424 | ---- | localhost | bans | Sleep   |  7826 |          | NULL             |
| 2425 | ---- | localhost | bans | Sleep   |  7707 |          | NULL             |
| 2426 | ---- | localhost | bans | Sleep   |  7706 |          | NULL             |
| 2427 | ---- | localhost | bans | Sleep   |  7610 |          | NULL             |
| 2428 | ---- | localhost | bans | Sleep   |  7586 |          | NULL             |
| 2430 | ---- | localhost | bans | Sleep   |  7558 |          | NULL             |
| 2431 | ---- | localhost | bans | Sleep   |  7498 |          | NULL             |
| 2432 | ---- | localhost | bans | Sleep   |  7438 |          | NULL             |
| 2434 | ---- | localhost | bans | Sleep   |  7378 |          | NULL             |
| 2435 | ---- | localhost | bans | Sleep   |  7318 |          | NULL             |
| 2436 | ---- | localhost | bans | Sleep   |  7257 |          | NULL             |
| 2546 | ---- | localhost | bans | Sleep   |    56 |          | NULL             |
| 2556 | ---- | localhost | bans | Sleep   |   689 |          | NULL             |
| 2586 | ---- | localhost | NULL | Query   |     0 | starting | show processlist |
+------+------+-----------+------+---------+-------+----------+------------------+
201 rows in set (0,00 sec)

Итого 200 соединений за примерно 3 часа, при лимите в 100 по умолчанию. Где-то они не закрываются.

**Comment by CrazyHackGUT** [comment]
( ._.)
(._. )
( ._. )
Надо в README.md сделать пометку, чтобы по серверному плагину писали в Issue #26 

Я сегодня вплотную хочу заняться этим плагином, как только своё чудо доделаю, если что.

**Comment by CrazyHackGUT** [comment]
Теперь проблемы быть не должно. Пробуйте.

**Comment by x3m77rus** [comment]
Проблемы нет.
