### ISSUE TITLE
Не работает скрытие флага из бана

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#44]
![image](https://cloud.githubusercontent.com/assets/13346898/21866155/a47d94f0-d851-11e6-879a-6774df465013.png)
![image](https://cloud.githubusercontent.com/assets/13346898/21866161/ab608674-d851-11e6-9bc5-a9cb0b384183.png)

**Comment by CrazyHackGUT** [comment]
Исправлено.
Администраторам флаг продолжает отображаться. Обычным пользователям - нет.

**Comment by Meowmurmur** [comment]
Флаг скрывается только из списка банов, в деталях бана флаг всё равно есть. Можно конечно и IP скрыть, но найдутся наверное люди, которые захотят скрыть флаги полностью, но не скрывая IP. :laughing:

**Comment by Meowmurmur** [comment]
Заметил ещё такую штуку - после скрытия флага, в деталях бана он есть, то страна отмечается как неизвестная, при этом во всех старых банах флаг не меняется.
