### ISSUE TITLE
Баг с поиском в системном логе

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#46]
![image](https://cloud.githubusercontent.com/assets/13346898/21961212/da3cb4d2-db0c-11e6-8098-ce8d8ee09567.png)
И после выбора админа пункт автоматически не выделяется (мб из-за бага)

**Comment by CrazyHackGUT** [comment]
Странно. Я вроде делал это... Ладно, посмотрю и исправлю.

**Comment by CrazyHackGUT** [comment]
Исправлено в 1.1.6.
