### ISSUE TITLE
Новая серверная часть

### ISSUE THREAD

**Issue by DemonEkb** [CrazyHackGUT/SB_Material_Design#55]
В новой серверной части бан проходит, но игрока не кикает. Так же игрок может свободно перезайти на сервер. Сервер отдает ошибку:
L 01/28/2017 - 02:26:43: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 01/28/2017 - 02:26:43: [SM] Native "Format" reported: Language phrase "Minutes" not found
L 01/28/2017 - 02:26:43: [SM] Displaying call stack trace for plugin "sourcebans.smx":
L 01/28/2017 - 02:26:43: [SM]   [0]  Line 1215, sourcebans.sp::VerifyInsert()

**Comment by CrazyHackGUT** [comment]
1. По серверной части уже имеется Issue, в который всё складывать и стоит. #26 
2. Не загружен файл переводов.
`Language phrase "Minutes" not found`
