### ISSUE TITLE
Не прогружается форма добавления мута/бана из-за символов в нике

### ISSUE THREAD

**Issue by Meowmurmur** [CrazyHackGUT/SB_Material_Design#59]
http://recordit.co/DzQx6XPSQ0
(Сначала сервер с новой серверной, потом со стандартным плагином от СБ)
\\\\\\\\\\\\\\\\
Только сейчас до меня дошло, что дело было в нике игрока -_-

**Comment by CrazyHackGUT** [comment]
Эм, лол, странно. Посмотрю... 
Черт знает, что там говнокодеры сб оставили...

**Comment by Meowmurmur** [comment]
Ещё узнал, что проблемным символом в нике является #, то есть, если ник для примера начинается так: iG.#, то оно не может получить данные вообще, кроме как начала ника, т.е. iG.

**Comment by CrazyHackGUT** [comment]
Это облегчает решение проблемы. Сейчас попробую поколдовать.

**Comment by CrazyHackGUT** [comment]
Проверьте. Должно быть теперь исправлено.

**Comment by Meowmurmur** [comment]
Вроде как нормально работает с фиксом, ну по возможности ещё на других игроках проверю.

**Comment by CrazyHackGUT** [comment]
Issue тогда пока что закрываю. Если что, откроете по новой.
