### ISSUE TITLE
host_info_show 2

### ISSUE THREAD

**Issue by TR1D** [CrazyHackGUT/SB_Material_Design#66]
Не отображается информация о сервере при host_info_show 2
csgo

**Comment by CrazyHackGUT** [comment]
Претензии на эту тему стоит писать в GitHub-репозитории сторонней библиотеки, которая используется в данном рефорке.
https://github.com/xPaw/PHP-Source-Query/

**Comment by CrazyHackGUT** [comment]
Автор библиотеки, вроде как, к слову, русский. Можно попытаться создать Issue на русском у него в репозитории, однако я бы написал на английском, чисто из уважения к американцам.
