### ISSUE TITLE
Критическая ошибка PHP

### ISSUE THREAD

**Issue by RED4911** [CrazyHackGUT/SB_Material_Design#68]
PHP Uncaught Error: Call to undefined method PDORow::MoveNext() in /var/www/ire/data/www/bans.ire.ru/pages/header.php:128 Stack trace: #0 /var/www/ire/data/www/bans.ire.ru/includes/system-functions.php(94): include() #1 /var/www/ire/data/www/bans.ire.ru/includes/page-builder.php(148): BuildPageHeader() #2 /var/www/ire/data/www/bans.ire.ru/index.php(39): include_once('/var/www/ire...') #3 {main} thrown /var/www/ire/data/www/bans.ire.ru/pages/header.php::128

**Comment by CrazyHackGUT** [comment]
Сб дев?

**Comment by RED4911** [comment]
да

**Comment by RED4911** [comment]
Это было и на Added PDO, updated Avatar Manager, но что то не пишет ни кто об этом.

**Comment by CrazyHackGUT** [comment]
Странно. Я тестировал вроде, и такого не вылезало. 
Ладно, посмотрю сегодня.

**Comment by CrazyHackGUT** [comment]
Не знаю, откуда у Вас PHP нашёл класс _PDORow_. Такого класса не существует. Существует только _CPDO_Result_, в котором как раз и имеется метод, который ищет PHP.
Попробуйте перекачать архив.

**Comment by RED4911** [comment]
Вот еще что вылезло https://i.gyazo.com/452679564909bc7345b746f52de1d377.png

**Comment by CrazyHackGUT** [comment]
Старый баг библиотеки, которая реализует AJAX. Проявляется только тогда, когда от сервера приходит много данных...

**Comment by RED4911** [comment]
Поставил последнюю версию выдает Parse error: syntax error, unexpected ';' in /www/pire/data/www/ire.ru/includes/CDB.php on line 48

**Comment by RED4911** [comment]
Линию 48 мне помогли исправить но дальше `Произошла фатальная ошибка PHP Uncaught Error: Call to undefined method PDORow::MoveNext() in /www/ire/data/www/ire.ru/pages/header.php:128 Stack trace: #0 /www/ire/data/www/ire.ru/includes/system-functions.php(94): include() #1 /www/ire/data/www/ire.ru/includes/page-builder.php(148): BuildPageHeader() #2 /www/mixempire/data/www/ire.ru/index.php(39): include_once('/www/...') #3 {main} thrown/wwwire/data/www/ire.ru/pages/header.php::128`

**Comment by CrazyHackGUT** [comment]
Пока что дев ставить не надо.

**Comment by RED4911** [comment]
Уже понял.

**Comment by CrazyHackGUT** [comment]
Сейчас вроде все косяки в дев исправлены. Просьба проверить, т.к. я повторить ошибку не могу.

**Comment by RED4911** [comment]
Parse error: syntax error, unexpected ';' in /var/www/mixempire/data/www/bans.mixempire.ru/includes/CDB.php on line 48

**Comment by RED4911** [comment]
Плюс я писал еще в теме про плагин, что админка слетает почему то у некоторых.

**Comment by RED4911** [comment]
НЕ могу зайти в админку никаким образом. [Tue Feb 28 00:39:26.543551 2017] [cgi:error] [pid 23434] [client 188.442.170.185:46378] AH01215: PHP Notice:  Use of undefined constant SB_ICONS_LOCATION - assumed 'SB_ICONS_LOCATION' in /var/www/ire/data/www/ire.ru/init.php on line 45, referer: http://ire.ru/

**Comment by RED4911** [comment]
В файле page.youraccount.php строка 31 почему то "Вы не должны быть здесь ><"

**Comment by RED4911** [comment]
Чистил кэш, куки не помогает. Вылетает в логах ошибка которая выше. Если зайти с другого браузера например интернет эксплорер то нормально заходит. С моего основного не заходит теперь.

**Comment by CrazyHackGUT** [comment]
> Parse error: syntax error, unexpected ';' in /var/www/ire/data/www/ire.ru/includes/CDB.php on line 48

Хи, странно, не закоммитил, наверное.
> Use of undefined constant SB_ICONS_LOCATION - assumed 'SB_ICONS_LOCATION'

Одной буквой промахнулся :(
> В файле page.youraccount.php строка 31 почему то "Вы не должны быть здесь ><"

Видимо, доработка менеджера пользователей всё ещё требуется.

**Comment by CrazyHackGUT** [comment]
Поправил класс работы с БД и "indefined constant SB_ICONS_LOCATION"

**Comment by CrazyHackGUT** [comment]
Поправил все остальные базовые классы, исправил утечку памяти нового менеджера пользовательских фотографий (аватарок).
К слову, в профиль меня пускает.

https://kruzefag.ru/SB_Dev/
```Login: test
Пароль: test```

**Comment by RED4911** [comment]
Произошла фатальная ошибка PHP Uncaught Error: Call to undefined method PDORow::MoveNext() in /var/www/ire/data/www/ire.ru/pages/header.php:128 Stack trace: #0 /var/www/ire/data/www/ire.ru/includes/system-functions.php(94): include() #1 /var/www/ire.ru/data/www/ire.ru/includes/page-builder.php(148): BuildPageHeader() #2 /var/www/ire.ru/data/www/ire.ru/index.php(39): include_once('/var/www/ire...') #3 {main} thrown /var/www/ire.ru/data/www/ire.ru/pages/header.php::128

**Comment by RED4911** [comment]
На твоем меня пускает на своем не могу проверить ошибка выше.

**Comment by CrazyHackGUT** [comment]
Покажите файл `/includes/CDB.php`, а конкретно класс `CPDO_Result` из него.

**Comment by RED4911** [comment]
return new CPDO_Result($statement, $params);

Полностью снес СБ и установил заново все

**Comment by CrazyHackGUT** [comment]
Не-не-не, меня интересует вот эта часть из Вашего файла:
![photo](http://i.imgur.com/JD65kvo.png)

**Comment by RED4911** [comment]
class CPDO_Result {
    private $hStatement;
    protected $EOF;
    protected $values;

    public function __construct($hStatement, $Params = array()) {
        try {
            $this->hStatement = $hStatement;
            $this->hStatement->execute($Params);
            $this->EOF = $this->hStatement->nextRowset();
        
            if ($this->EOF) {
                $this->MoveNext();
            }
        } catch (PDOException $e) {
            throw $e;
        }
    }

    public function MoveNext() {
        $this->values = $this->hStatement->fetch(PDO::FETCH_BOTH);
        $this->EOF = $this->hStatement->nextRowset();
    }
}

**Comment by RED4911** [comment]
Вроде все то же самое. Я же все становил и ничего не менял сам

**Comment by CrazyHackGUT** [comment]
Хм, странно. Можно в ЛС в Дискорде, ВК или Стиме данные от FTP-сервера?
В Дискорде меня можно найти [на канале рефорка](https://discord.gg/BrTP9Cu), Steam временно я посещаю [со своего левого аккаунта](http://steamcommunity.com/profiles/76561198020185461/), а ВК - [основной](https://vk.com/crazyhackgut).

**Comment by RED4911** [comment]
добавь меня в стим на твой нынешний акк http://steamcommunity.com/profiles/76561197993165287/

**Comment by RED4911** [comment]
Даже админа не могу добавить 
Произошла фатальная ошибка PHP Uncaught Error: Cannot access protected property CPDO_Result::$EOF in /var/www/ire/data/www/bans.ire.ru/pages/admin.admins.php:202 Stack trace: #0 /var/www/ire/data/www/bans.ire.ru/includes/admin.php(199): include() #1 /var/www/ire/data/www/bans.ire.ru/includes/page-builder.php(154): include('/var/www/mixemp...') #2 /var/www/ire/data/www/bans.ire.ru/index.php(39): include_once('/var/www/mixemp...') #3 {main} thrown /var/www/ire/data/www/bans.ire.ru/pages/admin.admins.php::202

**Comment by Meowmurmur** [comment]
Мб в версии PHP дело?

**Comment by RED4911** [comment]
Версия php это первое что я проверил. Дело не в этом.

**Comment by CrazyHackGUT** [comment]
> Даже админа не могу добавить, пишет в управлении админами
Произошла фатальная ошибка PHP Uncaught Error: Cannot access protected property CPDO_Result::$EOF 

Мой косяк. Исправлю.
Хотя странно, конечно. У меня с типом `protected` всё работает...

> А это пишет в управлении банами
Произошла фатальная ошибка PHP Uncaught Error: Call to undefined method CPDO_Result::RecordCount()

Не знал, что такое используется Сурсбанами, потому и не переносил из ADOdb. Перенесу.

**Comment by RED4911** [comment]
У тебя почему то все работает )))))

**Comment by RED4911** [comment]
L 02/28/2017 - 04:17:04: SourceMod error session started
L 02/28/2017 - 04:17:04: Info (map "awp_lego2") (file "errors_20170228.log")
L 02/28/2017 - 04:17:04: [SM] Exception reported: Script execution timed out
L 02/28/2017 - 04:17:04: [SM] Unable to load plugin "materialadmin.smx": Fatal error during plugin initialization (ext req)
L 02/28/2017 - 11:56:16: Error log file session closed.

**Comment by CrazyHackGUT** [comment]
Неактуально в связи с отправкой переноса PDO временно в чёрный ящик.
Как только появится снова время на реализацию такого грандиозного плана - возможно, переоткрою, и доделаю адекватно.
