### ISSUE TITLE
materialadmin plugin errors 

### ISSUE THREAD

**Issue by vBDSK** [CrazyHackGUT/SB_Material_Design#69]
L 02/13/2017 - 19:21:09: [SM] Exception reported: Script execution timed out
L 02/13/2017 - 19:21:09: [SM] Blaming: new_sb/materialadmin.smx
L 02/13/2017 - 19:21:09: [SM] Call stack trace:
L 02/13/2017 - 19:21:09: [SM]   [1] Line 1474, materialadmin/database.sp::SQL_Callback_QueryBekap
L 02/13/2017 - 19:22:22: [SM] Exception reported: Script execution timed out
L 02/13/2017 - 19:22:22: [SM] Blaming: new_sb/materialadmin.smx
L 02/13/2017 - 19:22:22: [SM] Call stack trace:
L 02/13/2017 - 19:22:22: [SM]   [1] Line 1474, materialadmin/database.sp::SQL_Callback_QueryBekap

**Comment by CrazyHackGUT** [comment]
Все проблемы с новым плагином необходимо направлять в Issue под номером #26
