### ISSUE TITLE
Баг с отображение замученных игроков на сервере

### ISSUE THREAD

**Issue by SovRedBit** [CrazyHackGUT/SB_Material_Design#71]
Привет крузя, проблема такова, когда заходишь в твой новый плагин и мутишь себя, то показывает что замучены все игроки на сервере сбоку от имени игрока в меню хотя они писать могут и при заходе к ним они отображаются как не замученные.

**Comment by CrazyHackGUT** [comment]
1). Это не мой плагин, а у Серого.
2). По проблемам с ним стоит писать ему.
3). Для проблем с новым плагином, существует целый Issue #26
