### ISSUE TITLE
Не могу поменять CSS

### ISSUE THREAD

**Issue by Ant1kkkkk** [CrazyHackGUT/SB_Material_Design#72]
Хочу сделать красивее с виду шаблон, редактирую в css файле, заливаю обратно, а остается то же самое, в чем проблема?

**Comment by CrazyHackGUT** [comment]
Кеш. Очевидно же.

**Comment by Ant1kkkkk** [comment]
Кэш чистил через настройки в sb, не помогло.

**Comment by vampir551** [comment]
При чем тут настройки СБ. Чисти кэш браузера

**Comment by CrazyHackGUT** [comment]
Кеш шаблона абсолютно не влияет на кеш Вашего браузера.

**Comment by CrazyHackGUT** [comment]
Если используется CloudFlare, то необходимо на их сайте так же очистить кеш.

**Comment by CrazyHackGUT** [comment]
Мне, кажется, что проблема решена. Тему закрываю.
