### ISSUE TITLE
Когда выйдет обновление?

### ISSUE THREAD

**Issue by IIIef** [CrazyHackGUT/SB_Material_Design#74]
Добрый день, скажите пожалуйста когда выедет обновление или уже вышло, но его не видно. Просто прошло как 3 месяца, наверное и не одной обновы. И где вот эта "Последняя актуальная версия: 1.1.6 (от 28.04.2017)" что-то ее ни где нельзя скачать.

**Comment by sasha54178** [comment]
Конечно нельзя скачать, ведь 28.04.2017 будет через 4 дня, это дата выхода обновы.

**Comment by CrazyHackGUT** [comment]
Дата обновления переносится на середину мая. Учёба не даёт нормально заниматься чем либо.

И любые вопросы со словом "когда", не имеют, как правило, конкретных ответов.

**Comment by IIIef** [comment]
Блин, а у меня походу уже 28 ))) CrazyHackGUT, понял спасибо за ответ.

**Comment by CrazyHackGUT** [comment]
Тема закрыта.
Как только обновление будет доделано, будет об этом объявлено в Дискорд-канале.
Если Вас там до сих пор нет, приглашаем: https://discord.gg/WgDtxfd
