### ISSUE TITLE
Ошибка соединения с сервером.

### ISSUE THREAD

**Issue by IIIef** [CrazyHackGUT/SB_Material_Design#76]
Добрый день, помогите решить проблему странную. Поменял базу обратно на опен сервер, а стояло все на вампсервере и в итоге тф2 серваки сурсбан не видит. Серваки и база все стоят на локалке. Раньше как-то решалась данная проблема на форуме. https://cloud.mail.ru/public/GWKg/kD8tR3xPD

**Comment by CrazyHackGUT** [comment]
Проверьте, подключено ли PHP-расширение **GMP**.

**Comment by IIIef** [comment]
Все супер заработало. Спасибо огромное.
