### ISSUE TITLE
Ваучеры, флаг для варнов.

### ISSUE THREAD

**Issue by medV3dkO** [CrazyHackGUT/SB_Material_Design#80]
Добавление множество ваучеров за раз, сделать особенный флаг веб админки для предупреждений админам на сервере

**Comment by CrazyHackGUT** [comment]
1). Множество ваучеров? Хз, может сделаю.
2). Особенный флаг веб-админки для выдачи предов? Может быть.
Вообще, изначально особенный флаг планировался, но посмотрев на то, как устроены эти флаги, желание пропало, т.к. возможны проблемы с уже установленными правами (рут внезапно превратится в чисто удаление админов, и тд тп).

**Comment by OkyHp** [comment]
На счет первого, есть еще просьба, если будет желание заняться, сделай возможность сразу удалить все использованные ваучеры, потому что удалять по одному, ждать пока перезагрузится страница, муторно. а через базу на прямую лучше сразу повеситься(веб хост арена - скорость...). Спасибо

**Comment by CrazyHackGUT** [comment]
В обслуживание системы в настройках добавлю.

**Comment by CrazyHackGUT** [comment]
Выполнено.
