### ISSUE TITLE
Проблема с ником админа

### ISSUE THREAD

**Issue by mrkos9i4ok** [CrazyHackGUT/SB_Material_Design#81]
Вообщем у админа был никнейм `INFARKT_/d.va/`
Но в admins.cfg он добавлялся,как
```
"INFARKT_"
{
  "d.va"
  {
  .....
  }
}
```
Из-за чего у него на сервере не было админки,есть решение таких проблем?

**Comment by CrazyHackGUT** [comment]
Нет, решение этой проблемы **нет** и **не существует** в природе. **Так работает движок Source**. Это он составляет конфиги на основе запросов плагинов. Плагин передаёт никнейм как полагается, но движок это по своему обрабатывает.

**Comment by CrazyHackGUT** [comment]
Хотя, можно попытаться соорудировать костыль. Но я не знаю, сработает ли. Вообщем, напиши мне [в Steam](https://kruzefag.ru/profiles/steam/) в ЛС. Завтра или послезавтра скину тестовую версию с костылем.

**Comment by voed** [comment]
@CrazyHackGUT нужно экранировать или удалять такие символы же

**Comment by CrazyHackGUT** [comment]
Экранизация не помогает.
И уже соорудил "костыль".
https://github.com/SB-MaterialAdmin/OldServer/blob/master/addons/sourcemod/scripting/sbpp_main.sp#L1660

**Comment by voed** [comment]
@CrazyHackGUT я юзаю такой сток в amxx, где-то подсмотрел давно
```sourcepawn
stock mysql_escape_string(dest[], len)
{
	replace_all(dest, len, "\\", "\\\\");
	replace_all(dest, len, "\0", "\\0");
	replace_all(dest, len, "\n", "\\n");
	replace_all(dest, len, "\r", "\\r");
	replace_all(dest, len, "\x1a", "\Z");
	replace_all(dest, len, "'", "\'");
	replace_all(dest, len, "^"", "\^"");
}
```
